"""Generate paper tables and a paired-seed figure from verified evidence.

Run only after collect_sensitivity.py has produced a complete archive and
that archive has been extracted into a dedicated evidence directory.
"""
import argparse
import hashlib
import json
from pathlib import Path

from aggregate_sensitivity import aggregate


def pm(record, digits=4, multiplier=100):
    return rf"${multiplier*record['mean']:.{digits}f}\pm{multiplier*record['sd']:.{digits}f}$"


def render(root, paper, summary_path):
    data = aggregate(root)
    cent = data["centering"]["aggregate"]
    mis = data["mismatch"]["aggregate"]
    outputs = {}
    macro_lines = ["% Generated by campaign/render_sensitivity.py from complete verified evidence."]

    def macro(name, value, digits=4, multiplier=100):
        macro_lines.append(rf"\newcommand{{\{name}}}{{{multiplier*value:.{digits}f}}}")

    for name, key in (("Pooled", "pooled"), ("Local", "local"), ("CenterDelta", "local_minus_pooled")):
        for suffix, stat in (("", "mean"), ("Sd", "sd")):
            macro("sens" + name + suffix, cent[key][stat], 6 if key == "local_minus_pooled" else 4)
    for name, key in (("MismatchMean", "test_mismatch_mean"), ("Consistent", "test_consistent"),
                      ("MismatchDelta", "test_consistent_minus_historical")):
        for suffix, stat in (("", "mean"), ("Sd", "sd")):
            macro("sens" + name + suffix, mis[key][stat], 6 if name == "MismatchDelta" else 4)
    macro("sensMismatchMax", mis["test_mismatch_maximum"]["maximum"], 4)
    macro("sensCenterMaxAbs", max(abs(v) for v in cent["local_minus_pooled"]["per_seed"]), 6)

    lines = [r"\begin{tabular}{lc}", r"\toprule", r"Centering convention & Mean relative error (\%) \\", r"\midrule"]
    for title, key in (("Historical retained pipeline", "historical"),
                       ("Pooled centering, paired rerun", "pooled"),
                       ("Fold-local centering, paired rerun", "local")):
        lines.append(title + " & " + pm(cent[key]) + r" \\")
    lines.extend([r"\midrule", "Fold-local minus pooled (percentage points) & " + pm(cent["local_minus_pooled"], 6) + r" \\", r"\bottomrule", r"\end{tabular}"])
    outputs["table_centering_sensitivity.tex"] = "\n".join(lines) + "\n"

    lines = [r"\begin{tabular}{lc}", r"\toprule", r"Fixed historical mean and kernel & Mean relative error (\%) \\", r"\midrule"]
    for title, key in (("Mean without correction", "test_base"), ("Historical residual labels", "test_historical"),
                       ("Inference-consistent residual labels", "test_consistent"),
                       ("Consistent correction or mean, validation-selected", "selected_test")):
        lines.append(title + " & " + pm(mis[key]) + r" \\")
    lines.extend([r"\midrule", "Consistent minus historical (percentage points) & " + pm(mis["test_consistent_minus_historical"], 6) + r" \\",
                  r"Mean propagated mismatch, relative norm (\%) & " + pm(mis["test_mismatch_mean"])+r" \\",
                  r"\bottomrule", r"\end{tabular}"])
    outputs["table_mismatch_sensitivity.tex"] = "\n".join(lines) + "\n"

    lines = [r"\begin{tabular}{llcccc}", r"\toprule",
             r"& & \multicolumn{2}{c}{Reduced error (\%)} & \multicolumn{2}{c}{Radiance error (\%)} \\",
             r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
             r"Band & Model & Recorded grid & Expanded grid & Recorded grid & Expanded grid \\", r"\midrule"]
    model_names = (("kernel_raw", "Raw input"), ("kernel_ard", "ARD input"),
                   ("mean_flat", "Flat-loss network"), ("dkr_flat", "Flat-feature head"),
                   ("combined", "Coordinate combination"))
    for band, title, command in (("o2", "O2", "Otwo"), ("wco2", "WCO2", "Wco"), ("sco2", "SCO2", "Sco")):
        group = data["oco_grids"][band]["aggregate"]
        for model, label in model_names:
            cells = [pm(group[scenario][model][metric], 3 if metric == "reduced" else 4)
                     for metric in ("reduced", "radiance") for scenario in ("recorded_grid", "expanded_grid")]
            lines.append(" & ".join([title, label] + cells) + r" \\")
        if band != "sco2":
            lines.append(r"\addlinespace")
        for name, model in (("Raw", "kernel_raw"), ("Head", "dkr_flat"), ("Combo", "combined")):
            for suffix, scenario in (("Old", "recorded_grid"), ("New", "expanded_grid")):
                for metric, end in (("reduced", "Red"), ("radiance", "Rad")):
                    macro("sens"+command+name+suffix+end, group[scenario][model][metric]["mean"], 3 if metric == "reduced" else 4)
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    outputs["table_grid_sensitivity.tex"] = "\n".join(lines) + "\n"
    outputs["sensitivity_macros.tex"] = "\n".join(macro_lines) + "\n"

    # Every dot is one paired seed comparison on the same public test block.
    # The two panels have separate y scales, stated explicitly in the caption.
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    with plt.rc_context({"font.family": "serif", "font.size": 9, "axes.spines.top": False,
                         "axes.spines.right": False, "pdf.fonttype": 42}):
        fig, axes = plt.subplots(1, 2, figsize=(6.6, 2.6), constrained_layout=True)
        for ax, record, title in zip(axes,
                (cent["local_minus_pooled"], mis["test_consistent_minus_historical"]),
                ("(a) Fold-local minus pooled", "(b) Consistent minus historical labels")):
            ax.axhline(0, color="0.6", lw=.8)
            ax.scatter(range(10), [100*v for v in record["per_seed"]], s=22, color="#245782", zorder=3)
            ax.axhline(100*record["mean"], color="#a34c26", lw=1, ls="--", label="Mean over seeds")
            ax.set(title=title, xlabel="Seed", ylabel="Error difference (percentage points)", xticks=range(10))
            ax.ticklabel_format(axis="y", style="sci", scilimits=(-3, 3), useMathText=True)
        axes[1].legend(frameon=False, fontsize=8)
        figures = paper / "figs"
        figures.mkdir(parents=True, exist_ok=True)
        fig.savefig(figures / "paired_implementation_sensitivity.pdf")
        plt.close(fig)
    for name, content in outputs.items():
        (paper / name).write_text(content, encoding="utf-8")
    summary_path.write_text(json.dumps(data, indent=2)+"\n", encoding="utf-8")
    paths = [paper/name for name in outputs] + [paper/"figs/paired_implementation_sensitivity.pdf", summary_path]
    receipt = dict(evidence_manifest_sha256=data["evidence_manifest_sha256"],
                   generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
                   outputs={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths})
    (paper/"sensitivity_generation.json").write_text(json.dumps(receipt,indent=2)+"\n",encoding="utf-8")
    print("Generated tables, macros, paired figure, and source-bound receipt")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--paper", required=True, type=Path)
    parser.add_argument("--summary", required=True, type=Path)
    args = parser.parse_args()
    render(args.root, args.paper, args.summary)
